trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - '**/*'

variables:
  ACR_LOGIN_SERVER: 'crwebdevcac01.azurecr.io'
  IMAGE_REPOSITORY: 'virecintelligencevirecwebapp'
  CONTAINER_NAME: 'main'
  K8S_NAMESPACE: 'default'
  K8S_DEPLOYMENT: 'virec-web-app'

stages:
  - stage: Build_Push
    displayName: Build & Push image to ACR
    jobs:
      - job: Build
        displayName: Docker build & push
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'sc-acr-crwebdevcac01'

          - bash: |
              set -euo pipefail
              cd "$(Build.SourcesDirectory)"
              DF="$(git ls-files | grep -E '(?i)(^|/)Dockerfile(\.[^/]+)?$' | head -n1 || true)"
              if [ -z "$DF" ]; then
                echo "##vso[task.logissue type=error]No Dockerfile found in repository."
                echo "##vso[task.complete result=Failed;]"
                exit 1
              fi
              echo "Discovered Dockerfile: $DF"
              CTX="$(dirname "$DF")"
              echo "Build context: $CTX"
              echo "##vso[task.setvariable variable=DOCKERFILE_PATH]$DF"
              echo "##vso[task.setvariable variable=BUILDCONTEXT_PATH]$(Build.SourcesDirectory)/$CTX"
            displayName: 'Detect Dockerfile & context'

          - task: Docker@2
            displayName: 'Build image'
            inputs:
              command: build
              containerRegistry: 'sc-acr-crwebdevcac01'
              repository: '$(IMAGE_REPOSITORY)'
              dockerfile: '$(DOCKERFILE_PATH)'
              buildContext: '$(BUILDCONTEXT_PATH)'
              tags: |
                $(Build.SourceVersion)
                latest

          - task: Docker@2
            displayName: 'Push image'
            inputs:
              command: push
              containerRegistry: 'sc-acr-crwebdevcac01'
              repository: '$(IMAGE_REPOSITORY)'
              tags: |
                $(Build.SourceVersion)
                latest

  - stage: Deploy_AKS
    displayName: Deploy to AKS
    dependsOn: Build_Push
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: Apply manifests & roll out
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: KubernetesManifest@1
            displayName: 'Deploy manifests (with image override)'
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'sc-aks-web-dev-cac-01'
              namespace: '$(K8S_NAMESPACE)'
              manifests: |
                k8s/deployment.yaml
              containers: |
                $(ACR_LOGIN_SERVER)/$(IMAGE_REPOSITORY):$(Build.SourceVersion)

          - task: Kubernetes@1
            displayName: 'kubectl set image'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'sc-aks-web-dev-cac-01'
              namespace: '$(K8S_NAMESPACE)'
              command: 'set'
              arguments: >
                image deployment/$(K8S_DEPLOYMENT)
                $(CONTAINER_NAME)=$(ACR_LOGIN_SERVER)/$(IMAGE_REPOSITORY):$(Build.SourceVersion)

          - task: Kubernetes@1
            displayName: 'kubectl rollout status'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'sc-aks-web-dev-cac-01'
              namespace: '$(K8S_NAMESPACE)'
              command: 'rollout'
              arguments: 'status deployment/$(K8S_DEPLOYMENT) --timeout=180s'
