trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - '**/*'

# Variables you might tweak
variables:
  ACR_LOGIN_SERVER: 'crwebdevcac01.azurecr.io'
  IMAGE_REPOSITORY: 'virecintelligencevirecwebapp'
  CONTAINER_NAME: 'main'
  K8S_NAMESPACE: 'default'
  K8S_DEPLOYMENT: 'virec-web-app'

stages:
  - stage: Build_Push
    displayName: Build & Push image to ACR
    jobs:
      - job: Build
        displayName: Docker build & push
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'sc-acr-crwebdevcac01'

          - task: Docker@2
            displayName: 'Build image'
            inputs:
              command: build
              repository: '$(IMAGE_REPOSITORY)'
              dockerfile: '**/Dockerfile'
              containerRegistry: 'sc-acr-crwebdevcac01'
              tags: |
                $(Build.SourceVersion)
                latest

          - task: Docker@2
            displayName: 'Push image'
            inputs:
              command: push
              repository: '$(IMAGE_REPOSITORY)'
              containerRegistry: 'sc-acr-crwebdevcac01'
              tags: |
                $(Build.SourceVersion)
                latest

          # Make the full image reference available to next stage
          - task: Bash@3
            name: setimage
            displayName: 'Set image variable'
            inputs:
              targetType: 'inline'
              script: |
                echo "##vso[task.setvariable variable=FULL_IMAGE;isOutput=true]$(ACR_LOGIN_SERVER)/$(IMAGE_REPOSITORY):$(Build.SourceVersion)"
        # expose output variable for next stage
        outputs:
          imageRef: setimage.FULL_IMAGE

  - stage: Deploy_AKS
    displayName: Deploy to AKS
    dependsOn: Build_Push
    variables:
      FULL_IMAGE_FROM_BUILD: $[ stageDependencies.Build_Push.Build.outputs['imageRef'] ]
    jobs:
      - job: Deploy
        displayName: kubectl rollout
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: KubernetesManifest@1
            displayName: 'Create/Update manifests (first-time safe)'
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'sc-aks-web-dev-cac-01'
              namespace: '$(K8S_NAMESPACE)'
              manifests: |
                k8s/deployment.yaml
              containers: |
                $(FULL_IMAGE_FROM_BUILD)

          # (Optional) Force update deployment’s image explicitly
          - task: Kubernetes@1
            displayName: 'kubectl set image'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'sc-aks-web-dev-cac-01'
              namespace: '$(K8S_NAMESPACE)'
              command: 'set'
              arguments: >
                image deployment/$(K8S_DEPLOYMENT)
                $(CONTAINER_NAME)=$(FULL_IMAGE_FROM_BUILD)

          - task: Kubernetes@1
            displayName: 'kubectl rollout status'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'sc-aks-web-dev-cac-01'
              namespace: '$(K8S_NAMESPACE)'
              command: 'rollout'
              arguments: 'status deployment/$(K8S_DEPLOYMENT) --timeout=180s'
